Animate success checkmark
sindresorhus/CircularProgress pull request #21
Opened 2019-04-01 00:31 UTC by allewun

Fixes #5 

![2019-03-31 17 18 23](https://user-images.githubusercontent.com/1256911/55297355-24fc4800-53da-11e9-94eb-888a2175e2cc.gif)

Not sure how fancy you wanted the animation to be, but this seems to fit with the current aesthetic.

2019-04-01 03:43 UTC, allewun commented
Slightly more organic animation curves:

![2019-03-31 20 42 29](https://user-images.githubusercontent.com/1256911/55302343-8d0c5780-53f5-11e9-8139-5b14cda9f991.gif)

2019-04-17 09:52 UTC, sindresorhus commented
This is looking great! It perfectly fits into the existing style of the circle. 👌

I would like to see some particles/sparkles, as mentioned in the #5.

Some more ideas:

- https://lottiefiles.com/2536-sent-successfully
- https://lottiefiles.com/433-checked-done
- https://lottiefiles.com/72-favourite-app-icon
- https://lottiefiles.com/1818-success-animation
- https://lottiefiles.com/432-done-button

Or at least something that makes it feel more organic.

It should still stay minimal. Just would be nice with a tiny bit of delightfulness.

Not sure whether the particles should come from the checkmark or the circle though. I have feeling it would better to come from the checkmark as then we could contain the animation to the circle. Having it go outside the circle might complicate it's usage, as we cannot assume what kind of surface/situation it will be used.

2019-04-17 09:55 UTC, sindresorhus requested changes

2019-04-17 09:55 UTC, sindresorhus commented on Sources/CircularProgress/CircularProgress.swift
> +	Show an animating `CheckmarkView` instead of `100%`.
```suggestion
	Show an animated checkmark instead of `100%`.
```

2019-04-17 09:55 UTC, sindresorhus commented on Sources/CircularProgress/CheckmarkView.swift
> +class CheckmarkView: NSView {
```suggestion
final class CheckmarkView: NSView {
```

2019-04-17 09:55 UTC, sindresorhus commented on Sources/CircularProgress/CheckmarkView.swift
> +	override init(frame frameRect: NSRect) {
```suggestion
	override init(frame frameRect: CGRect) {
```

2019-04-17 09:57 UTC, sindresorhus commented
If the user hovers the circular progress while the progress turns to 100%, I think we should force-show the checkmark view because they cannot cancel anyway when it's done.

2019-04-18 00:35 UTC, allewun commented
@sindresorhus Even with those examples, animations are pretty subjective. Would you be able to provide some more direction?

Side note, the reason I didn't initially think to add any flourishes was to keep the library a bit more general. I thought sparkles might feel out of place in a "serious" application ("Would Apple do this?" is the question I ask myself. See below.) Thoughts?

![2019-04-17 17 29 03](https://user-images.githubusercontent.com/1256911/56329028-7fb1d580-6136-11e9-9b90-9b7c784fc355.gif)

2019-04-19 05:37 UTC, allewun commented
Force-show checkmark at 100%:
![2019-04-18 22 36 40](https://user-images.githubusercontent.com/1256911/56408705-8ae62d80-622a-11e9-9c41-07531726b09b.gif)

2019-05-04 13:28 UTC, sindresorhus commented
> Even with those examples, animations are pretty subjective. Would you be able to provide some more direction?

I don't really know. Was hoping you had some suggestions. I guess we can just drop it and keep it simple.

---

I feel like the easing/animation could be slightly tweaked. I prefer the speed/easing of the Apple checkmark:

![Untitled](https://user-images.githubusercontent.com/170270/57179714-ccbdd780-6eaa-11e9-9d42-314055e49110.gif)
![Untitled2](https://user-images.githubusercontent.com/170270/57179716-ccbdd780-6eaa-11e9-81f2-782c8c3b3677.gif)

2019-05-26 22:39 UTC, allewun commented
@sindresorhus Thanks for your patience. How's this?

![loop](https://user-images.githubusercontent.com/1256911/58387900-bc8da980-7fcb-11e9-9cf2-34dce8d208f7.gif)

2019-05-27 04:05 UTC, merged

2019-05-27 04:05 UTC, sindresorhus commented
Looks good now. Thanks for working on it 🙌