Add ability to hide label
sindresorhus/CircularProgress pull request #32
Opened 2021-03-17 22:51 UTC by rcobelli

Add `isLabelHidden` property. In response to #31

2021-03-18 14:21 UTC, sindresorhus commented
It still shows the label briefly when hovering over the progress circle and then out again. It also doesn't work with `.showCheckmarkAtHundredPercent = false`.

2021-03-18 14:21 UTC, sindresorhus requested changes

2021-03-18 14:21 UTC, sindresorhus commented on Sources/CircularProgress/CircularProgress.swift
> +	private var hiddenLabelObserver: NSKeyValueObservation?
This is not used anywhere.

2021-03-18 14:50 UTC, rcobelli commented on Sources/CircularProgress/CircularProgress.swift
> +	private var hiddenLabelObserver: NSKeyValueObservation?
Resolved in daf3113

2021-03-19 08:40 UTC, merged

2021-03-19 08:40 UTC, sindresorhus commented
Thanks :)